#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from hms_export.compare import compare_records, compare_records_exact, load_records  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description="Compare DataHub baseline output with Spark MCP output")
    parser.add_argument("--baseline", required=True, type=Path, help="original DataHub file sink file/directory")
    parser.add_argument("--candidate", required=True, type=Path, help="Spark MCP file/directory")
    parser.add_argument("--report", type=Path, help="write full JSON report")
    parser.add_argument("--strict", action="store_true", help="also compare aspects not generated by this project")
    parser.add_argument("--exact", action="store_true", help="compare exact aspect keys and values without normalization")
    args = parser.parse_args()
    try:
        baseline = load_records(args.baseline)
        candidate = load_records(args.candidate)
        report = (
            compare_records_exact(baseline, candidate)
            if args.exact
            else compare_records(baseline, candidate, strict=args.strict)
        )
    except Exception as exc:
        print(f"comparison failed: {exc}", file=sys.stderr)
        return 2
    rendered = json.dumps(report, ensure_ascii=False, indent=2)
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(rendered + "\n", encoding="utf-8")
    summary = report["summary"]
    print(
        f"equal={report['equal']} baseline={summary['baseline_aspects']} "
        f"candidate={summary['candidate_aspects']} missing={summary['missing_in_candidate']} "
        f"extra={summary['extra_in_candidate']} different={summary['different_aspects']}"
    )
    if not report["equal"]:
        print(rendered)
    return 0 if report["equal"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
